models/Locales.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "locales".
 *
 * @property int $id
 * @property string $name
 *
 * @property SourceMessage[] $sourceMessages
 */
class Locales extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'locales';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
        ];
    }

    public function getSourceMessages()
    {
        return $this->hasMany(SourceMessage::className(), ['category' => 'id'])->orderBy('order');
    }
}

controllers/LocalesController.php
<?php

namespace app\controllers;

use app\models\Languages;
use app\models\Message;
use app\models\SourceMessage;
use Yii;
use app\models\Locales;
use yii\data\ActiveDataProvider;
use app\components\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * LocalesController implements the CRUD actions for Locales model.
 */
class LocalesController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['access']['rules'] = [
            [
                'allow' => true,
                'roles' => ['admin'],
            ]
        ];

        return $behaviors;
    }

    /**
     * Lists all Locales models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Locales::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Locales model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Locales();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['update', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Locales model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {

            $exists = $model->sourceMessages;
            if (count($exists)) {
                SourceMessage::loadMultiple($exists, Yii::$app->request->post());
                if (SourceMessage::validateMultiple($exists)) {
                    foreach ($exists as $m) {
                        $m->save(false);
                    }
                }

                $messagesData = Yii::$app->request->post('Message', []);

                foreach ($exists as $srcModel) {

                    foreach ($messagesData as $code => $value) {
                        list($srcId, $langCode) = explode('_', $code);

                        if ($srcId != $srcModel->id) continue;

                        $messModel = Message::findOne(['id' => $srcId, 'language' => $langCode]);
                        if (!$messModel) {
                            $messModel = new Message();
                            $messModel->id = $srcModel->id;
                            $messModel->language = $langCode;
                        }
                        $messModel->translation = $value;
                        $messModel->save(true);

                        unset($messagesData[$code]);
                    }

                }
            }



            $srcModels = [];
            foreach (Yii::$app->request->post('newSourceMessage', []) as $i => $data) {
                $newModel = new SourceMessage();
                $newModel->attributes = $data;
                $newModel->category = (string) $model->id;
                if ($newModel->save()) {
                    $srcModels[$i] = $newModel;
                }
            }


            $messagesData = Yii::$app->request->post('newMessage', []);
            foreach ($srcModels as $index => $srcModel) {

                foreach ($messagesData as $code => $value) {
                    list($srcIndex, $langCode) = explode('_', $code);

                    if ($srcIndex != $index) continue;

                    $messModel = new Message();
                    $messModel->id = $srcModel->id;
                    $messModel->language = $langCode;
                    $messModel->translation = $value;
                    $messModel->save(true);

                    unset($messagesData[$code]);
                }
            }

            return $this->redirect(['update', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionImport($id)
    {
        $model = $this->findModel($id);

        $file = UploadedFile::getInstanceByName('import_file');

        if ($file) {

            $csv = array_map('str_getcsv', file($file->tempName));

            // langs
            foreach ($csv[0] as $i => $langCode) {
                if ($i == 0) continue;

                $lModel = Languages::findOne(['code' => $langCode]);
                if (!$lModel) {
                    $lModel = new Languages(['code' => $langCode, 'name' => $langCode]);
                    $lModel->save();
                }
            }

            array_walk($csv, function(&$a) use ($csv) {
                $a = array_combine($csv[0], $a);
            });
            array_shift($csv);

            $result = [];
            foreach ($csv as $item) {
                $key = $item['var_name'];
                array_shift($item);
                $result[$key] = $item;
            }


            SourceMessage::deleteAll(['category' => $id]);

            $i = 1;
            foreach ($result as $ph => $messages) {

                $src = new SourceMessage([
                    'category' => $id,
                    'message' => $ph,
                    'order' => $i++
                ]);

                if ($src->save()) {
                    foreach ($messages as $lang => $str) {
                        $message = new Message([
                            'id' => $src->id,
                            'language' => $lang,
                            'translation' => $str,
                        ]);
                        $message->save(false);
                    }
                }

            }
        }

        return $this->redirect(['update', 'id' => $id]);
    }

    public function actionDeleteSrc($id)
    {
        $model = SourceMessage::findOne(['id' => $id]);

        if ($model) {
            $model->delete();
        }

        return $this->asJson([]);
    }

    public function actionDelete($id)
    {
        $model = $this->findModel($id);

        SourceMessage::deleteAll(['category' => $model->id]);
        $model->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Locales model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Locales the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Locales::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/locales/_grid.php
<?php

use app\models\Languages;
use app\models\Message;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Locales */


?>

    <div class="locales-form" data-app-controller="loc_AddRow">

        <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

        <br>
        <br>

        <table class="table table-striped table-hover locales-table js-sort">
            <tr>
                <th></th>
                <th>Placeholder</th>

                <?php foreach (Languages::find()->all() as $lang) {?>
                    <th><?= $lang->name?> (<?= $lang->code?>)</th>
                <?php } ?>

                <th></th>
            </tr>


            <?php foreach ($model->sourceMessages as $i => $srcModel) { ?>
                <tr class="js-sort-item">
                    <td class="js-handle locales-table__sort-handle">
                        <i class="fa fa-arrows" aria-hidden="true"></i>
                    </td>
                    <td>
                        <?= Html::activeTextInput($srcModel, '['.$i.']message', ['class' => ''])?>
                        <?= Html::activeHiddenInput($srcModel, '['.$i.']order', ['class' => 'js-sort-order'])?>
                    </td>

                    <?php foreach (Languages::find()->all() as $lang) {
                        $message = Message::find()->andWhere(['language' => $lang->code, 'id' => $srcModel->id])->one()?>

                        <td>
                            <?php echo Html::textInput("Message[{$srcModel->id}_{$lang->code}]", $message ? $message->translation : null); ?>
                        </td>

                    <?php } ?>

                    <td>
                        <?= Html::a('X', ['delete-src', 'id' => $srcModel->id], ['class' => 'btn btn-danger btn-sm js-delete'])?>
                    </td>
                </tr>
            <?php } ?>


            <tr class="js-proto" style="display: none">
                <td class="js-handle locales-table__sort-handle">
                    <i class="fa fa-arrows" aria-hidden="true"></i>
                </td>
                <td>
                    <?= Html::textInput('message', null, ['class' => 'js-src-control'])?>
                    <?= Html::hiddenInput('order', null, ['class' => 'js-src-control js-sort-order'])?>
                </td>

                <?php foreach (Languages::find()->all() as $lang) { ?>

                    <td>
                        <?php echo Html::textInput("{$lang->code}", null, ['class' => 'js-cell-control']); ?>
                    </td>

                <?php } ?>

                <td>
                    <?= Html::a('X', ['delete-src', 'id' => -1], ['class' => 'btn btn-danger btn-sm js-delete'])?>
                </td>
            </tr>

        </table>


        <div class="form-group clearfix">
            <a class="btn btn-default pull-left js-add-proto">+</a>
        </div>


        <div class="form-group">
            <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
        </div>


        <?php ActiveForm::end(); ?>

    </div>

views/locales/_import.php
<?php

use app\models\Languages;
use app\models\Message;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Locales */


?>

<div class="locales-form" >

    <?php $form = ActiveForm::begin([
        'action' => Url::toRoute(['locales/import', 'id' => $model->id]),
        'options' => ['enctype' => 'multipart/form-data']
    ]); ?>

    <?= Html::fileInput('import_file') ?>

    <br>

    <div class="form-group">
        <?= Html::submitButton('Import', ['class' => 'btn btn-success']) ?>
    </div>


    <?php ActiveForm::end(); ?>

</div>

views/locales/create.php
<?php


/* @var $this yii\web\View */
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Html;

/* @var $model app\models\Locales */

$this->title = 'Create Locale';
$this->params['breadcrumbs'][] = ['label' => 'Locales', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="locales-create">

    <div class="locales-form">

        <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

        <div class="form-group">
            <?= Html::submitButton('Save To Continue', ['class' => 'btn btn-success']) ?>
        </div>

        <?php ActiveForm::end(); ?>

    </div>

</div>

views/locales/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Locales';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="locales-index">

    <p>
        <?= Html::a('Create Locale', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            'id',
            'name',

            ['class' => 'yii\grid\ActionColumn', 'template' => '{update} {delete}'],
        ],
    ]); ?>
</div>

views/locales/update.php
<?php

use app\models\Languages;
use app\models\Message;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Locales */

$this->title = 'Update Locale: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Locales', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="locales-update">

    <!-- Nav tabs -->
    <ul class="nav nav-tabs">
        <li class="active"><a href="#grid" data-toggle="tab">Grid</a></li>
        <li><a href="#import" data-toggle="tab">Import</a></li>
    </ul>

    <br>

    <!-- Tab panes -->
    <div class="tab-content">
        <div class="tab-pane active" id="grid">
            <?= $this->render('_grid', compact('model'))?>
        </div>

        <div class="tab-pane" id="import">
            <?= $this->render('_import', compact('model'))?>
        </div>
    </div>


</div>

views/locales/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Locales */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Locales', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="locales-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'code',
        ],
    ]) ?>

</div>